# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'CognitiveConcierge' do
pod 'JSQMessagesViewController','7.3.4'

pod 'Alamofire', '3.5.0'
pod 'Freddy', '2.1.0'
pod 'GooglePlaces', '2.0.1'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'            
        end
    end
end

end
